name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: listing files
        run: |
          pwd
          ls
      - name: Checkout
        uses: actions/checkout@v1
      - name:  simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:  
          who-to-greet: Dennis
      - name: running time action action action
        run: echo "${{ steps.greet.outputs.time }}"

