name: Actions Workflow

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: listing files
        run: |
          pwd
          ls -la
      - name: Checkout
        uses: actions/checkout@v1
      - name: after checkout
        run: | 
          pwd
          ls -la
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}"
          #git clone git@github:$GITHUB_REPOSITORY
          #git checkout $GITHUB_SHA
      - name:  simple JS Action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:  
          who-to-greet: Dennis
      - name: running time action action action
        run: echo "${{ steps.greet.outputs.time }}"
