name: Create issue on commit
on:
- push
jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
    - name: checking out actions
      uses: actions/checkout@v1
    - name: push random file
      run: |
        pwd
        ls -a
        git init
        git clone "https://$GITHUB_ACTOR:${{ secrets }}@github.com/$GITHUB_REPOSITORY.git"
        git config --global user.email "hartingerdennis@gmail.com"
        git config --global user.name "my-bot"
        ls -a  
        echo $RANDOM >> random.txt
        ls -a
        pwd
        git add .
        git commit -m "Random file"
        git push
    - name: Create issue using REST API
      run: |
        curl --request POST \
        --url https://api.github.com/repos/${{ github.repository }}/issues \
        --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
        --header 'content-type: application/json' \
        --data '{
          "title": "Automated issue for commit: ${{ github.sha }}",
          "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
          }' 
