name: Running on labs

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: running ls
        run: ls    
      - name: running file maker
        run: touch test
      - name: running directory lister
        run: ls -la 
