name: cronjob

on:
  repository_dispatch:
    types: [build] 
#  schedule:
#    - cron: "0/5 * * * *"
#    - cron: "0/6 * * * *"

  pull_request: 
    types: [closed, assigned, opened, reopened]
    
  
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: payload
        run: echo ${{ github.event.client-payload.env }}
      - name: running list
        run: ls -la
 
