name: nameofaction

on: 
  schedule:
    - cron: "0/5 * * * *"
    - cron: "0/6 * * * *"

  pull_request: [closed, assigned, opened, reopened]
    

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: running list
        run: ls -la
 
