name: cronjob

on:
  push:
    branches:
      - master
      - "feature/*" # matches feature/feata, feature/featb
      - "!feature/featC"
#    tags:
#      - v1.*
#    paths:
#      - "**.js"
#      - "!**.txt"
#    tags-ignore     
#    braches-ignore:
#  repository_dispatch:
#    types: [build] 
#  schedule:
#    - cron: "0/5 * * * *"
#    - cron: "0/6 * * * *"

#  pull_request: 
#    types: [closed, assigned, opened, reopened]
    
  
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: payload
        run: echo ${{ github.event.client_payload.env }}
      - name: running list
        run: ls -la
 
